### ISSUE TITLE
Error when building app in Docker container and running assets:precompile

### ISSUE THREAD

**Issue by jaredlt** [esminc/activejob-google_cloud_tasks-http#1]
I build my app in a Docker container and use assets:precompile so the app has faster cold starts. When deploying this on production I hit an error because the environment variable I use for Google credentials was not available for the precompile step (assets:precompile runs all config and initializers).

Error in Docker build:

```
Step #1: Step 17/23 : RUN SECRET_KEY_BASE=1 bundle exec rake assets:precompile
Step #1:  ---> Running in c8abbe14a1b3
Step #1: rake aborted!
Step #1: TypeError: no implicit conversion of nil into String
Step #1: /usr/src/app/config/environments/production.rb:125:in `block in <top (required)>'
```

relevant production.rb snippet (with some sensitive data obscured):

```ruby
    config.active_job.queue_adapter = ActiveJob::GoogleCloudTasks::HTTP::Adapter.new(
      project: 'my-project',
      location: 'europe-west2',
      url: 'https://www.example.com/jobs',
      client: Google::Cloud::Tasks.new(
        version: :v2beta3,
        credentials: JSON.parse(ENV["GOOGLE_CLOUD_PRODUCTION_KEYFILE"]) # production.rb:125
      )
    )
```

The environment variable does not exist yet, nor do I want to include it in the build steps. It's annoying because this is being called by assets:precompile which in no way affects Active Job or Google Cloud Tasks. Ideally it just wouldn't run this at all.

After a few too many hours of frustration I came across a reasonable workaround (via https://stackoverflow.com/a/58017606/3471900):

```ruby
  unless ARGV.include?("assets:precompile") # wrap the config so it doesn't run when assets:precompile is called
    config.active_job.queue_adapter = ActiveJob::GoogleCloudTasks::HTTP::Adapter.new(
      project: 'my-project',
      location: 'europe-west2',
      url: 'https://www.example.com/jobs',
      client: Google::Cloud::Tasks.new(
        version: :v2beta3,
        credentials: JSON.parse(ENV["GOOGLE_CLOUD_PRODUCTION_KEYFILE"])
      )
    )
  end
```

Ideally this would be handled natively by the gem, but if not, perhaps adding a section to the readme or wiki would help others and future me :) Quick draft suggestion:

**Error when calling assets:precompile?**

If you call assets:precompile, all configs and initializers are loaded. If you load your credentials via environment variables they may not be available and the adapter will error. To solve this, wrap the `queue_adapter` config in a `unless ARGV.include?("assets:precompile")` condition. Eg.

```ruby
unless ARGV.include?("assets:precompile") # prevents running on assets:precompile
  Rails.application.config.active_job.queue_adapter = ActiveJob::GoogleCloudTasks::HTTP::Adapter.new(
    project: 'my-project',
    location: 'europe-west2',
    # ...
  )
end
```

PS. Thank you for the gem! It works great and got me up and running with Cloud Tasks super quickly :)

**Comment by hibariya** [comment]
Hello, @jaredlt. I'm sorry for the late reply.

It would be nice if we do not have to consider `assets:precompile` on initialization. I added a section about that as you suggested since I do not have a good idea to support that for now. Thank you for the suggestion! I added it almost as it was.
