### ISSUE TITLE
Unable to access standard rails logger from rack app

### ISSUE THREAD

**Issue by MarkBennett** [esminc/activejob-google_cloud_tasks-http#2]
Hi @hibariya, great gem. Cloud Tasks look like they'll make my async tasks way simpler and cheaper to host!

I'm having trouble with some of my jobs failing however and don't seem to be seeing any output in the normal Rails log. I'm assuming that's because Rack is unable to access the Rails loggers, but I'm new to mounting Rack apps inside Rails ones so I apologize if I'm just confused.

Is there an easy way to expose the Rails logger to your Rack component? Alternately, would you be open to a PR which extracted the logic for running the jobs from your Rack component so I could mix it into a Rails controller?

Thank-you, and please let me know if you need more specific information to give an answer. I'm away from my code right now but can get you code samples later.

Cheers!

**Comment by hibariya** [comment]
Hi @MarkBennett . I don't understand why you cannot see error messages or something in Rails logs when a job fails. Does the log-outputs have any other content? It would be a big help if you could provide an example code (or repository) to reproduce the issue.

**Comment by MarkBennett** [comment]
Just out with the fam but I'll extract a case and file a proper bug report. Thank you for the great gem!

**Comment by MarkBennett** [comment]
Hey @hibariya. I believe this may have been related to my service worker for the job processor not having the right permissions required to log in Google Cloud. I've since replaced this code with a simple Rails controller on my end so I can no longer confirm.

Closing. Thanks!

**Comment by hibariya** [comment]
I see. Thanks for sharing!
