### ISSUE TITLE
Getting errors with new API

### ISSUE THREAD

**Issue by ghost** [esminc/activejob-google_cloud_tasks-http#6]
I'm receiving the following:

```
ArgumentError (wrong number of arguments (given 3, expected 0; required keywords: project, location, queue))
```

This is when adapter tries to call `queue_path`. This is likely due to changes in Google's Ruby libraries.

**Comment by hibariya** [comment]
Hello @thelucid. Thanks for letting me know. As you mentioned, it seems that the client API has changed in google-cloud-tasks 2.0 or later ([migration guide](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-tasks/MIGRATING.md)). I will try to make this gem use the new API.
